name: Docker Image CI

on:
  push:
    branches:
      - main  # Trigger the workflow on 'main' branch push
  pull_request:
    branches:
      - main  # Trigger the workflow on PR to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Versione più recente

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Versione aggiornata
        # Abilitazione della build multi-architettura (opzionale)

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Versione aggiornata
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password or token from secrets

      - name: Build Docker image with commit hash tag
        run: |
          COMMIT_HASH=${{ github.sha }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hamsterstunnel:$COMMIT_HASH .
        
      - name: Push Docker image to Docker Hub with commit hash
        run: |
          COMMIT_HASH=${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/hamsterstunnel:$COMMIT_HASH

      - name: Tag and Push latest image
        if: github.ref == 'refs/heads/main'  # This will only run if the push is to the main branch
        run: |
          COMMIT_HASH=${{ github.sha }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/hamsterstunnel:$COMMIT_HASH ${{ secrets.DOCKER_USERNAME }}/hamsterstunnel:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/hamsterstunnel:latest

